controller_manager:
  ros__parameters:
    update_rate: 50

    trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    
trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - l_sho_pitch
      - r_sho_pitch
      - l_sho_roll
      - r_sho_roll
      - l_el
      - r_el
      - l1
      - r1
      - l3
      - r3

diff_drive_base_controller:
  ros__parameters:
    left_wheel_names:
      - l4
    right_wheel_names:
      - r4

    wheel_separation: 0.481
    #wheel_separation: 0.430
    wheel_per_side: 1
    wheel_radius: 0.093

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    odom_frame_id: odom
    base_frame_id: base_link

#position_controller:
#  ros__parameters:
#    joints:
#      - l1
#      - r1
#      - l3
#      - r3
#      - l4
#      - r4

#velocity_controller:
#  ros__parameters:
#    joints:
#      - l4
#      - r4
    

    
