controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    position_controller:
      type: position_controllers/JointGroupPositionController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    

trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - l_sho_pitch
      - l_sho_roll
      - l_el
      - r_sho_pitch
      - r_sho_roll
      - r_el

diff_drive_base_controller:
  ros__parameters:
    left_wheel_names:
      - l4
    right_wheel_names:
      - r4

    wheel_separation: 0.552
    wheels_per_side: 1
    wheel_radius: 0.25

    wheel_seperation_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    command_interfaces:
      - velocity

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link

forward_velocity_controller:
  ros__parameters:
    joints:
      - l4
      - r4
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity 

forward_position_controller:
  ros__parameters:
    joints:
      - l1
      - l3
      - r1
      - r3
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

position_controller:
  ros__parameters:
    joints:
      - l_sho_pitch
      - l_sho_roll
      - l_el
      - r_sho_pitch
      - r_sho_roll
      - r_el
      - l1
      - l3
      - r1
      - r3

velocity_controller:
  ros__parameters:
    joints:
      - l4
      - r4
    

    
